### ISSUE TITLE
Configuration should be passed from the main package

### ISSUE THREAD

**Issue by bobbytables** [namely/broadway#103]
Right now we have an `env` package (https://github.com/namely/broadway/tree/master/env) that handles reading environment variables and exposing them to packages that import it.

While this was fine to get going, we really really should be loading this from the `main` package that starts and keeps broadway running.

I propose using [cobra](https://github.com/spf13/cobra) to handle parsing flags and setting configuration.

**Comment by therealplato** [comment]
#110

**Comment by therealplato** [comment]
#121

**Comment by bobbytables** [comment]
Godd stuff @therealplato
