### ISSUE TITLE
alias commands

### ISSUE THREAD

**Issue by therealplato** [namely/broadway#56]
This is hard to remember
I should be able to use either `/broadway setvar...` or `/broadway setvars...` from slack
I should be able to use either `/broadway destroy...` or `/broadway delete...` from slack

- [ ] Alias setvar/setvars
- [ ] Alias destroy/delete
- [ ] Update help command to show all commands

**Comment by macat** [comment]
+1

**Comment by therealplato** [comment]
https://github.com/namely/broadway/pull/107
