### ISSUE TITLE
Get instance info

### ISSUE THREAD

**Issue by macat** [namely/broadway#98]
Show info about the instance with `/broadway info <playbook_id> <id>`.  
This should list variables and display the state of the instance.

- [x] Parse the `info` subcommand from slack
- [x] Document the `info` command in `help`
- [x] Look up instance
- [x] Display ids, deployment status, variable keys/values
- [x] Display age

**Comment by therealplato** [comment]
https://github.com/namely/broadway/pull/105

**Comment by therealplato** [comment]
<img width="372" alt="screen shot 2016-07-18 at 6 56 19 pm" src="https://cloud.githubusercontent.com/assets/764725/16933163/58749ed2-4d19-11e6-9d78-97a21a1489fd.png">

**Comment by therealplato** [comment]
https://github.com/namely/broadway/pull/106
