### ISSUE TITLE
Ability to lock an instance

### ISSUE THREAD

**Issue by bobbytables** [namely/broadway#99]
It would be super convenient to lock an instance. This could be good for moratoriums, qa cycles, etc.

It could operate like:

```sh
/bw lock {playbook} {instance}
```

Any attempt to deploy a locked instance would yield a response in Slack:

```sh
/bw deploy {playbook} {instance}

Broadway: "The instance is currently locked by @bobbytables"
```

```sh
/bw destroy {playbook} {instance}

Broadway: "The instance is currently locked by @bobbytables"
```

**Comment by edisgreat** [comment]
![image](https://cloud.githubusercontent.com/assets/1005183/16457898/2e2d7fd2-3deb-11e6-80bf-e76c46b7d982.png)

**Comment by therealplato** [comment]
`/bw lock broadway master` to limit shenanigans
